import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "CineVerse",
  description: "Generated by CineVerse",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
